// LOGIN ACTION
export const REQUEST_REGISTER = 'REQUEST_REGISTER';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REQUEST_VALID_TOKEN = 'REQUEST_VALID_TOKEN';
export const UPDATE_USER = 'UPDATE_USER';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

// NOTIFICATION ACTION
export const SET_FCM_TOKEN = 'SET_FCM_TOKEN';

// COMPANY
export const LOAD_CITY_DATA = 'LOAD_CITY_DATA';
export const LOAD_CITY_DATA_SUCCESS = 'LOAD_CITY_DATA_SUCCESS';
export const LOAD_DISTRICT = 'LOAD_DISTRICT';
export const LOAD_DISTRICT_SUCCESS = 'LOAD_DISTRICT_SUCCESS';
export const LOAD_WARD = 'LOAD_WARD';
export const LOAD_WARD_SUCCESS = 'LOAD_WARD_SUCCESS';
export const LOAD_WARD_FAIL = 'LOAD_WARD_FAIL';
export const GET_LIST_COMPANY = 'GET_LIST_COMPANY';
export const SET_LIST_COMPANY_SUCCESS = 'SET_LIST_COMPANY_SUCCESS';
export const CREATE_COMPANY = 'CREATE_COMPANY';
// CUSTOMER
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAIL = 'CREATE_CUSTOMER_FAIL';
export const CLEAR_CUSTOMER = 'CLEAR_CUSTOMER';
export const GET_LIST_CUSTOMER = 'GET_LIST_CUSTOMER';
export const SET_LIST_CUSTOMER_SUCCESS = 'SET_LIST_CUSTOMER_SUCCESS';

// TYPE CONFIG
export const GETDISTRICT = 'GETDISTRICT';
export const GETWARD = 'GETWARD';
export const LOAD_ALL_CONFIG = 'LOAD_ALL_CONFIG';
export const LOAD_CONFIG_SUCCESS = 'LOAD_CONFIG_SUCCESS';
export const UPDATE_PULL_REFESH = 'UPDATE_PULL_REFESH';
export const RESET_ALL_STATE = 'RESET_ALL_STATE';
export const RESET_CLICK_IN_APP = 'RESET_CLICK_IN_APP';
export const CLICKED_IN_APP = 'CLICKED_IN_APP';
export const LOAD_CITY_SUCCESS = 'LOAD_CITY_SUCCESS';
export const LOAD_CITY = 'LOAD_CITY';

// ORDER
export const GET_LIST_ORDER = 'GET_LIST_ORDER';
export const SET_LIST_DRAFT_SUCCESS = 'SET_LIST_DRAFT_SUCCESS';
export const SET_LIST_DRAFT_FAILED = 'SET_LIST_DRAFT_FAILED';
export const CREATE_ORDER = 'CREATE_ORDER';
export const SET_ORDER_SUCCESS = 'SET_ORDER_SUCCESS';
export const SET_ORDER_FAIL = 'SET_ORDER_FAIL';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const SET_LIST_SALE_SUCCESS = 'SET_LIST_SALE_SUCCESS';
export const SET_LIST_SALE_FAILED = 'SET_LIST_SALE_FAILED';
export const SET_LIST_PROCCESS_SUCCESS = 'SET_LIST_PROCCESS_SUCCESS';
export const SET_LIST_PROCCESS_FAILED = 'SET_LIST_PROCCESS_FAILED';
export const SET_LIST_DONE_SUCCESS = 'SET_LIST_DONE_SUCCESS';
export const SET_LIST_DONE_FAILED = 'SET_LIST_DONE_FAILED';
export const SET_LIST_CANCEL_SUCCESS = 'SET_LIST_CANCEL_SUCCESS';
export const SET_LIST_CANCEL_FAILED = 'SET_LIST_CANCEL_FAILED';
export const CLEAR_ORDER_LOCAL = 'CLEAR_ORDER_LOCAL';
export const SET_LIST_CONFIRM_SUCCESS = 'SET_LIST_CONFIRM_SUCCESS';
export const SET_LIST_CONFIRM_FAILED = 'SET_LIST_CONFIRM_FAILED';
export const ASSIGN_ORDER = 'ASSIGN_ORDER';
export const REJECT_ORDER = 'REJECT_ORDER';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const SET_LIST_PRINTED_SUCCESS = 'SET_LIST_PRINTED_SUCCESS';
export const SET_LIST_STORED_SUCCESS = 'SET_LIST_STORED_SUCCESS';
export const SET_LIST_DESIGN_SUCCESS = 'SET_LIST_DESIGN_SUCCESS';
export const SET_LIST_FEEDBACK_DESIGN_SUCCESS = 'SET_LIST_FEEDBACK_DESIGN_SUCCESS';
export const SET_LIST_DESIGNED_SUCCESS = 'SET_LIST_DESIGNED_SUCCESS';
export const SET_LIST_PRINTING_SUCCESS = 'SET_LIST_PRINTING_SUCCESS';
export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const GET_ORDER_STATUS_HISTORY = 'GET_ORDER_STATUS_HISTORY';
export const SET_LIST_DELIVERING_SUCCESS = 'SET_LIST_DELIVERING_SUCCESS';
// SEARCH ORDER
export const SEARCH_ORDER = 'SEARCH_ORDER';
export const SEARCH_ORDER_SUCCESS = 'SEARCH_ORDER_SUCCESS';
export const SEARCH_ORDER_FAILED = 'SEARCH_ORDER_FAILED';
// NOTIFICATION
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const SET_LIST_NOTIFICATION = 'SET_LIST_NOTIFICATION';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
